### ISSUE TITLE
TypeError: start_utt() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by dragoon** [Mattze96/pocketsphinx-python#1]
The error from the subject appears when pressing "start pocketsphinx" button. Then recognition does not work.

**Comment by Mattze96** [comment]
If you get a decoder error, caused by wrong locales do this: LANG=''; LC_ALL=''; ./main.py

**Comment by Mattze96** [comment]
Sorry, i found the bug. fixed it in the latest commit.

**Comment by dragoon** [comment]
Thanks!
